name-template: 'v$RESOLVED_VERSION 🚀'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'hotfix'
  - title: '📝 Documentation'
    labels:
      - 'docs'
  - title: '🔧 Maintenance'
    labels:
      - 'chore'
      - 'refactor'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' 

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## What's Changed 🔍

  $CHANGES

  ## 🚀 New Features
  $FEATURES

  ## 🐛 Bug Fixes
  $BUGFIXES

  ## 📦 Dependencies
  $DEPENDENCIES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
