services:
  - type: web
    name: knowledge-library
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.local_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
